### ISSUE TITLE
I get https not supported or disabled in libcurl

### ISSUE THREAD

**Issue by anilng** [vszakats/harbour-deps#5] opened 2016-05-30 13:40 UTC
When I call curl -X POST 'https://....

I thought this library was SSL enabled.

**Comment by vszakats** [comment] 2016-05-30 13:54
HTTPS is one of the main focus with these builds, so it should be enabled.

What does `curl -V` tell?

**Comment by anilng** [comment] 2016-05-30 14:03
Attached is the response.

**Comment by vszakats** [comment] 2016-05-30 14:08
Can't see the attachment. Can you just paste it here?

**Comment by anilng** [comment] 2016-05-30 14:12
C:\Users\XYZ\Desktop\CURL\curl-7.49.0-win32-mingw\curl-7.49.0-win32-mingw\bin>curl
-v 'https://.......'
* Protocol "'https" not supported or disabled in libcurl
* Closing connection -1
curl: (1) Protocol "'https" not supported or disabled in libcurl

**Comment by vszakats** [comment] 2016-05-30 14:22
It'd still be important to see the output of `curl -V` (note the uppercase `-V`).

I can't reproduce the problem locally:
```
C:\test\curl-7.49.0-win32-mingw\bin>curl.exe -v https://example.com

* Rebuilt URL to: https://example.com/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 93.184.216.34...
* Connected to example.com (93.184.216.34) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
[...]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=Los Angeles; O=Internet Corporation for Assigned Names and Numbers; OU=Technology; CN=www.example.org
*  start date: Nov  3 00:00:00 2015 GMT
*  expire date: Nov 28 12:00:00 2018 GMT
*  subjectAltName: host "example.com" matched cert's "example.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
} [5 bytes data]
> GET / HTTP/1.1
> Host: example.com
> User-Agent: curl/7.49.0
> Accept: */*
> 
{ [5 bytes data]
< HTTP/1.1 200 OK
< Cache-Control: max-age=604800
< Content-Type: text/html
< Date: Mon, 30 May 2016 14:19:51 GMT
< Etag: "359670651+ident"
< Expires: Mon, 06 Jun 2016 14:19:51 GMT
< Last-Modified: Fri, 09 Aug 2013 23:54:35 GMT
< Server: ECS (iad/18CB)
< Vary: Accept-Encoding
< X-Cache: HIT
< x-ec-custom-error: 1
< Content-Length: 1270
< 
{ [5 bytes data]
[...]
```

**Comment by anilng** [comment] 2016-05-30 14:31
C:\Users\XXX\Desktop\CURL\curl-7.49.0-win32-mingw\curl-7.49.0-win32-mingw\bin>
curl -V https://....

curl 7.49.0 (i386-pc-win32) libcurl/7.49.0 OpenSSL/1.0.2h zlib/1.2.8 WinIDN
libssh2/1.7.0 nghttp2/1.10.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3
pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz
TLS-SRP HTTP2

**Comment by vszakats** [comment] 2016-05-30 14:37
Thanks. This means the version is correct and `https` is supported as listed amongst `Protocols:`.

**Comment by vszakats** [comment] 2016-05-30 14:38
Here's the answer: http://bartwullems.blogspot.hu/2013/08/curl-1-protocol-not-supported-or.html

Closing.

**Closed by vszakats** 2016-05-30 14:38 UTC

**Comment by anilng** [comment] 2016-05-30 14:42
Thanks.
